### ISSUE TITLE
robot_state_t version?

### ISSUE THREAD

**Issue by tkoolen** [JuliaRobotics/DrakeLCMTypes.jl#1]
Thanks for doing the tedious work.

Unfortunately, it looks like

https://github.com/JuliaRobotics/DrakeLCMTypes.jl/blob/2c9aedb5253ae075a97cb10f8a420e9bfda80c14/src/robot_state_t.jl#L1-L13

isn't the same as

https://github.com/tkoolen/HumanoidLCMSim.jl/blob/885c5255c6d4c3ee4da3c07c8d695546ef149e62/src/lcmtypes/robot_state_t.jl#L1-L11

Which version of Drake did you base this on?

**Comment by rdeits** [comment]
That's just Drake's lcmt_robot_state which has always (at least back to 2013) been completely different than bot_core's robot_state_t (I don't know why). The LCM simulator uses the one from bot_core, which is in my PR to BotCoreLCMTypes: https://github.com/JuliaRobotics/BotCoreLCMTypes.jl/pull/2/files#diff-4ae80e3201377b045891bf3c11e72d58

**Comment by tkoolen** [comment]
Ah, great. Thanks.
